flask_gaming/models.py
from . import db
from sqlalchemy.ext.hybrid import hybrid_property
from flask import current_app


class User(db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    real_money_wallet = db.relationship(
        'RealMoneyWallet', uselist=False, backref='user')
    bonus_money_wallets = db.relationship('BonusMoneyWallet', uselist=True)
    bets = db.relationship('Bet', uselist=True)
    wins = db.relationship('Win', uselist=True)

    @hybrid_property
    def bonus_money_sum(self):
        return sum(bm.balance for bm in self.bonus_money_wallets if bm.depleted is False)

    def __init__(self, username=None, email=None, password_hash=None):
        self.username = username
        self.email = email
        self.password_hash = password_hash

    def __repr__(self):
        return '<User({}) {} >'.format(str(self.id), self.username)

    def save(self):
        db.session.add(self)
        db.session.commit()


class RealMoneyWallet(db.Model):

    __tablename__ = 'real_money_wallets'

    def __init__(self, balance=None):
        self.balance = balance

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False, unique=True)
    balance = db.Column(db.Float, default=0)

    def __repr__(self):
        return '<RealMoneyWallet {}>'.format(self.balance)


class BonusMoneyWallet(db.Model):

    __tablename__ = 'bonus_money_wallets'

    def __init__(self, balance=None):
        self.initial_balance = balance
        self.balance = balance

    @hybrid_property
    def cash_in_possible(self):
        return self.initial_balance * current_app.config['WAGERING_REQUIREMENT'] <= sum(b.amount for b in self.bets)

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    initial_balance = db.Column(db.Float, default=0)
    balance = db.Column(db.Float, default=0)
    depleted = db.Column(db.Boolean, default=False)
    bets = db.relationship('Bet', uselist=True)

    def __repr__(self):
        return '<BonusMoneyWallet {}>'.format(self.balance)


class Bet(db.Model):

    __tablename__ = 'bets'

    def __init__(self, amount, amount_type='real', bonus_money_wallet_id=None):
        self.amount = amount
        self.amount_type = amount_type
        self.bonus_money_wallet_id = bonus_money_wallet_id

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    bonus_money_wallet_id = db.Column(db.Integer, db.ForeignKey('bonus_money_wallets.id'), nullable=True)
    amount = db.Column(db.Float, nullable=False, default=0)
    amount_type = db.Column(db.Enum('real', 'bonus'), nullable=False, server_default=("real"))


class Win(db.Model):

    __tablename__ = 'wins'

    def __init__(self, amount, amount_type='real', bonus_money_wallet_id=None):
        self.amount = amount
        self.amount_type = amount_type
        self.bonus_money_wallet_id = bonus_money_wallet_id

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    bonus_money_wallet_id = db.Column(db.Integer, db.ForeignKey('bonus_money_wallets.id'), nullable=True)
    amount = db.Column(db.Float, nullable=False, default=0)
    amount_type = db.Column(db.Enum('real', 'bonus'), nullable=False, server_default=("real"))

flask_gaming/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_migrate import Migrate

db = SQLAlchemy()
bcrypt = Bcrypt()
config = None


def create_app(config_filename=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_pyfile(config_filename)
    initialize_extensions(app)
    register_blueprints(app)
    return app


def initialize_extensions(app):
    bcrypt.init_app(app)
    db.init_app(app)
    from . import models # noqa
    Migrate(app, db)


def register_blueprints(app):
    from flask_gaming.registration import registration
    from flask_gaming.auth import auth
    from flask_gaming.game import game
    from flask_gaming.payment import payment

    app.register_blueprint(registration, url_prefix='/registration')
    app.register_blueprint(auth, url_prefix='/auth')
    app.register_blueprint(game, url_prefix='/game')
    app.register_blueprint(payment, url_prefix='/payment')

flask_gaming/game/__init__.py
from flask import Blueprint
game = Blueprint('game', __name__)

from . import routes # noqa

flask_gaming/game/routes.py
from . import game
from flask import render_template, request, session, current_app
from flask_gaming.helpers import login_required
from flask_gaming.models import User
from flask_gaming.game_play import GamePlay


@game.route('/home')
@login_required
def index():
    return render_template('home.html')


@game.route('/place-bet', methods=['GET', 'POST'])
@login_required
def place_bet():
    if request.method == 'POST':
        user = User.query.get(session['user_id'])
        game_play = GamePlay(current_app.config, user)
        game_play.spin()
    return render_template('place-a-bet.html')

flask_gaming/payment/__init__.py
from flask import Blueprint
payment = Blueprint('payment', __name__)

from . import routes # noqa

flask_gaming/payment/routes.py
from . import payment
from flask import render_template, request, session
from flask_gaming.helpers import login_required
from flask_gaming.cashier import Cashier
from flask_gaming.models import User
from flask import current_app as app


@payment.route('/deposit', methods=('GET', 'POST'))
@login_required
def deposit():
    if request.method == "GET":
        return render_template('deposit.html')
    if request.method == "POST":
        user = User.query.get(session['user_id'])
        cashier = Cashier(app.config)
        cashier.deposit(user, float(request.form['amount']))
        return render_template('deposit.html')


@payment.route('/withdraw', methods=('GET', 'POST'))
@login_required
def withdraw():
    if request.method == "GET":
        return render_template('withdraw.html')
    if request.method == "POST":
        user = User.query.get(session['user_id'])
        cashier = Cashier(app.config)
        cashier.withdraw(user, float(request.form['amount']))
        return render_template('withdraw.html')

flask_gaming/templates/deposit.html
{% extends 'layout.html' %}

{% block content %}
{% include 'menu.html' %}

<div class="card bg-light">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Deposit</h4>
            <form action="{{url_for('payment.deposit')}}" method="POST">
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-dollar-sign"></i> </span>
                    </div>
                    <input name="amount" class="form-control" placeholder="Amount" type="text">
                </div> <!-- form-group// -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Deposit </button>
                </div> <!-- form-group// -->      
            </form>
        </article>
{% endblock %}

flask_gaming/templates/home.html
{% extends 'layout.html' %}

{% block content %}
{% include 'menu.html' %}

<div class="card bg-light">
    <br/>
    <center><h1>Welcome to Flask Gaming {{ session['username'] }}!</h1></center>
    <br/>
</div>
{% endblock %}

flask_gaming/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Flask Gaming</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
    
    <div class="container">
        <br/>
        {% block content %}{% endblock %}
    </div> 
    
    <br><br>
</body>
</html>

flask_gaming/templates/login.html
{% extends 'layout.html' %}

{% block content %}
    <div class="card bg-light">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Login</h4>
            <form action="{{url_for('auth.login')}}" method="POST">
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                    </div>
                    <input name="username" class="form-control" placeholder="User name" type="text">
                </div> <!-- form-group// -->
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input name="password" class="form-control" placeholder="Your password" type="password">
                </div> <!-- form-group// -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Login </button>
                </div> <!-- form-group// -->      
                <p class="text-center">Don't have an account? <a href="{{url_for('registration.index')}}">Create one</a> </p>                                                                 
            </form>
        </article>
    </div> <!-- card.// -->
{% endblock %}

flask_gaming/templates/menu.html
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        <a class="p-2 text-muted" href="{{url_for('game.index')}}">Home</a>
        <a class="p-2 text-muted" href="{{url_for('payment.deposit')}}">Deposit</a>
        <a class="p-2 text-muted" href="{{url_for('payment.withdraw')}}">Withdraw</a>
        <a class="p-2 text-muted" href="{{url_for('game.place_bet')}}">Place a bet</a>
        <a class="p-2 text-muted" href="{{url_for('auth.logout')}}"><b>({{ session['username'] }})</b> Logout </a>
    </nav>
</div>

flask_gaming/templates/place-a-bet.html
{% extends 'layout.html' %}

{% block content %}
{% include 'menu.html' %}

<div class="card bg-light">
    <article class="card-body mx-auto" style="max-width: 400px;">
        <h4 class="card-title mt-3 text-center">Let's play some spins</h4>
        <form action="{{url_for('game.place_bet')}}" method="POST">
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> Spin and Win!!! </button>
            </div>
        </form>
    </article>
</div> <!-- card.// -->
{% endblock %}

flask_gaming/templates/registration.html
{% extends 'layout.html' %}

{% block content %}
    <div class="card bg-light">
    <article class="card-body mx-auto" style="max-width: 400px;">
        <h4 class="card-title mt-3 text-center">Create Account</h4>
        <form action="{{url_for('registration.index')}}" method="POST">
        <div class="form-group input-group">
            <div class="input-group-prepend">
                <span class="input-group-text"> <i class="fa fa-user"></i> </span>
             </div>
            <input name="username" class="form-control" placeholder="User name" type="text">
        </div> <!-- form-group// -->
        <div class="form-group input-group">
            <div class="input-group-prepend">
                <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
             </div>
            <input name="email" class="form-control" placeholder="Email address" type="email">
        </div> <!-- form-group// -->
        <div class="form-group input-group">
            <div class="input-group-prepend">
                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
            </div>
            <input name="password" class="form-control" placeholder="Your password" type="password">
        </div> <!-- form-group// -->
        <div class="form-group input-group">
            <div class="input-group-prepend">
                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
            </div>
            <input name="password_repeat" class="form-control" placeholder="Repeat password" type="password">
        </div> <!-- form-group// -->                                      
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block"> Create Account  </button>
        </div> <!-- form-group// -->      
        <p class="text-center">Have an account? <a href="{{url_for('auth.login')}}">Log In</a> </p>                                                                 
    </form>
    </article>
    </div> <!-- card.// -->
{% endblock %}

flask_gaming/templates/withdraw.html
{% extends 'layout.html' %}

{% block content %}
{% include 'menu.html' %}

<div class="card bg-light">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Withdraw</h4>
            <form action="{{url_for('payment.withdraw')}}" method="POST">
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-dollar-sign"></i> </span>
                    </div>
                    <input name="amount" class="form-control" placeholder="Amount" type="text">
                </div> <!-- form-group// -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Withdraw </button>
                </div> <!-- form-group// -->      
            </form>
        </article>
{% endblock %}